In [1]:
from theano import *

Using gpu device 0: GeForce GTX 960 (CNMeM is enabled with initial size: 70.0% of memory, cuDNN 5005)


In [68]:
import numpy

scale_vector = [4] * 4
scale_vector.extend([1] * 3)
scale_vector = numpy.asarray(scale_vector)

In [69]:
scale_vector

array([4, 4, 4, 4, 1, 1, 1])

In [70]:
vector_1 = numpy.asarray([0.5, 0.3, 0.2, 0.1, 0, 1, 0, 1] * 50)
vector_2 = numpy.asarray([0.1, 0.1, 0.3, 0.3, 1, 0, 0, 1] * 50)

vector_1 = vector_1.reshape((50, 8))
vector_2 = vector_2.reshape((50, 8))

In [71]:
scale_vector * vector_1[0, 0:7]

array([ 2. ,  1.2,  0.8,  0.4,  0. ,  1. ,  0. ])

In [72]:
loss_piece = tensor.sum(tensor.mul(scale_vector, tensor.square(vector_1[:, 0:7] - vector_2[:, 0:7])), axis=1)

In [73]:
loss_piece.eval()

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [74]:
obj = vector_1[:, 7]

loss = tensor.mul(obj, loss_piece)

In [75]:
loss = tensor.sum(loss)

In [76]:
loss.eval()

array(150.0)